### ISSUE TITLE
Complement syntax of ...

### ISSUE THREAD

**Issue by hax** [devsnek/proposal-unused-function-parameters#5]
As https://github.com/hax/proposal-deiter propose, `...` could also be used to skip unused params.

```js
function f(..., x) {}
```

Note such syntax has limitation (can only skip continuous params once) and have different semantic (`(?, ?, x)` means only use the third argument, `(..., x)` means only use the last argument).

**Comment by devsnek** [comment]
I'm not planning to address such syntax in this proposal.
